version: "3.2"
services:
  jaeger:
    image: jaegertracing/all-in-one:1.21
    ports:
      - 14268:14268
      - 14269:14269
      - 16686:16686

  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    links:
      - jaeger:jaeger
    volumes:
      - ./grafana/:/etc/grafana/provisioning/

  pgsql:
    image: postgres:9.6
    container_name: pgsql
    restart: always
    ports:
    - "9241:5432"
    volumes:
    - ./data.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
     - POSTGRES_PASSWORD=pass
     - POSTGRES_USER=user
     - POSTGRES_DB=mydb
     - POSTGRES_HOST_AUTH_METHOD=trust
    command: ["postgres", "-c", "max_connections=10"]

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379
      - '6380:6379'